development:
 adapter: postgresql
 host: localhost
 database: development
 username: development 
 password: 

test:
 adapter: postgresql
 host: localhost
 database: test
 username: t
 
production:
 adapter: postgresql
 host: localhost
 database: roldaxhwh
 username: roldaxhwh
 password: FUIUT(OYITOYFI*%E(OTY
