development:
 adapter: postgresql
 host: localhost
 database: development
 username: development 
 password: F

test:
 adapter: postgresql
 host: localhost
 database: test
 username: F
 
production:
 adapter: postgresql
 host: localhost
 database: roldaxhwh
 username: roldaxhwh
 password: F
